<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30" started-at="2021-10-26T21:34:12Z" finished-at="2021-10-26T21:34:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30" started-at="2021-10-26T21:34:12Z" finished-at="2021-10-26T21:34:12Z">
      <class name="practice.collections.codes.ExceptionTest">
        <test-method status="PASS" signature="NumberFormatException()[pri:0, instance:practice.collections.codes.ExceptionTest@394df057]" name="NumberFormatException" duration-ms="9" started-at="2021-10-26T21:34:12Z" finished-at="2021-10-26T21:34:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NumberFormatException -->
      </class> <!-- practice.collections.codes.ExceptionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
